apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: iqw6h1r4q-dotnet-basic 
  janus-idp.io/tekton: iqw6h1r4q-dotnet-basic
  backstage.io/kubernetes-id: iqw6h1r4q-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iqw6h1r4q-dotnet-basic
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml